### ISSUE TITLE
Support serverless use cases (Vault-Zero)

### ISSUE THREAD

**Issue by bbros-dev** [joemiller/vault-token-helper#25]
We configure Vault server-less (Vault-Zero). 

For use cases such as bootstrapping infrastructure, and personal secret management (keepassxc replacement).

With this setup we encounter:

```
$ vault-token-helper list --extended
VAULT_ADDR               display_name  ttl  renewable  policies  
----------               ------------  ---  ---------  --------  
http://127.0.0.100:8200  ** ERROR **   error encountered setting up default configuration: open /etc/vault.d/client-certs/client-cert.pem: no such file or directory
```

**Comment by joemiller** [comment]
Can you provide some more info on this configuration? I'm not familiar with vault-zero. I am intrigued though.

**Comment by bbros-dev** [comment]
Vault-Zero is my script - nothing more.  It uses HTTP only so just unset and disable all Vault HTTPS settings:

```
export VAULT_TOKEN="$(secret-tool lookup vault zero policy admin|head)"
export VAULT_ADDR=http://127.0.0.100:8200
export VAULT_CLIENT_KEY=
export VAULT_CLIENT_CERT=
export VAULT_CACERT=
```

**Comment by joemiller** [comment]
@bbros-dev Thanks for the info. I'll take a look at this and think about the best way to handle. Your idea about detecting http makes sense.

**Comment by joemiller** [comment]
@bbros-dev I may need your help reproducing this.

Here is what I've tried and what the result was:

`run.sh`:
```sh
#!/bin/sh

export VAULT_ADDR=http://127.0.0.1:8200
export VAULT_CLIENT_KEY=
export VAULT_CLIENT_CERT=
export VAULT_CACERT=

vault server -dev -dev-root-token-id=root
```

Start the http vault server: `./run.sh &`

Add token to the token store:

```console
$ VAULT_ADDR=http://127.0.0.1:8200 vault login                          
Token (will be hidden): root
```

Run the extended list cmd:

```console
$ vault-token-helper list -e
VAULT_ADDR                                                                                     display_name          ttl         renewable  policies  
----------                                                                                     ------------          ---         ---------  --------  
http://127.0.0.1:8200                                                                          token                 0s          false      [root]
```

Stop the server and try list again:

```console
$ vault-token-helper list -e
VAULT_ADDR                                                                                     display_name          ttl         renewable  policies  
----------                                                                                     ------------          ---         ---------  --------  
http://127.0.0.1:8200                                                                          ** ERROR **           Get "http://127.0.0.1:8200/v1/auth/token/lookup-self": dial tcp 127.0.0.1:8200: connect: connection refused
```

I do not have any other `VAULT_*` env vars set:
```console
$ env grep | VAULT
$
```

This is on macOS with vault v1.7.1 installed via homebrew. I wonder if I would get different behavior on linux using a packaged version of vault since I'm not familiar with that `/etc/vault.d` convention and wonder if that's some default.

**Comment by bbros-dev** [comment]
To be clear you have none of those environment variables present?
Something equivalent to:

```
env -i vault-token-helper list --extended
```

Correct?

**Comment by bbros-dev** [comment]
Very strange indeed:

```
$ env -i /usr/local/bin/vault-token-helper list --extended
Error: Unable to initialize backend '': Specified keyring backend not available
```

I'll have to dig in.

**Comment by joemiller** [comment]
I'm working on this error message right now. An arch user reported this and it turned out that the 99designs/keyring lib was unable to detect an available backend. In that case installing gnome-keyring solved the issue by making the secret-service backend availabl.e

I will probably at least add a debug flag/env that is passed to the 99designs/keyring lib to show a bit more about what's going on in this situation. For example adding this in `pkg/store/store.go` would show logs from the keyring lib about why a usable backend could not be found:

```go
 // New creates a new Store from a keyring.Config
 func New(cfg keyring.Config) (*Store, error) {
+       if os.Getenv("KEYRING_DEBUG") != "" {
+               keyring.Debug = true
+       }
+
```

**Comment by bbros-dev** [comment]
@joemiller, can you indicate the Vault version after which it'll be possible to set only `VAULT_ADDR` to a htttp://... and have Vault 'Just-Work'(TM)?

**Comment by joemiller** [comment]
@bbros-dev I can't reproduce your issue.
